import os
import random
import re
import requests
import io
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime
from google import genai # NEW SDK IMPORT
from pypdf import PdfReader

# --- CONFIGURATION ---
CATEGORIES = ['cs.CV', 'cs.AI', 'cs.LG', 'cs.CL', 'cs.RO']
CATEGORY_NAMES = {
    'cs.CV': 'Computer Vision',
    'cs.AI': 'Artificial Intelligence',
    'cs.LG': 'Machine Learning',
    'cs.CL': 'NLP',
    'cs.RO': 'Robotics'
}

# Configure Gemini Client (New SDK)
# Uses the same secret key, no changes needed in Settings
API_KEY = os.environ.get("GEMINI_API_KEY")
client = None
if API_KEY:
    client = genai.Client(api_key=API_KEY)

def fetch_random_paper():
    selected_category = random.choice(CATEGORIES)
    print(f"Selected Category: {selected_category}")
    
    url = f'http://export.arxiv.org/api/query?search_query=cat:{selected_category}&start=0&max_results=30&sortBy=submittedDate&sortOrder=descending'
    
    try:
        with urllib.request.urlopen(url) as response:
            data = response.read()
        
        root = ET.fromstring(data)
        entries = root.findall('{http://www.w3.org/2005/Atom}entry')
        if not entries: return None

        random_entry = random.choice(entries)
        
        pdf_link = random_entry.find('{http://www.w3.org/2005/Atom}id').text.replace("/abs/", "/pdf/") + ".pdf"
        
        return {
            "title": random_entry.find('{http://www.w3.org/2005/Atom}title').text.replace('\n', ' ').strip(),
            "date": random_entry.find('{http://www.w3.org/2005/Atom}published').text[:10],
            "link": random_entry.find('{http://www.w3.org/2005/Atom}id').text,
            "pdf_link": pdf_link,
            "category": CATEGORY_NAMES.get(selected_category, selected_category)
        }
    except Exception as e:
        print(f"Error fetching metadata: {e}")
        return None

def extract_text_from_pdf(pdf_url):
    print(f"Downloading PDF: {pdf_url}...")
    try:
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
        }
        response = requests.get(pdf_url, headers=headers)
        
        if response.status_code != 200:
            print(f"Failed to download PDF. Status Code: {response.status_code}")
            return None
            
        f = io.BytesIO(response.content)
        reader = PdfReader(f)
        
        text = ""
        # Read first 7 pages (Gemini 2.5 has a huge context window, we can afford more)
        for page in reader.pages[:7]: 
            text += page.extract_text() + "\n"
        return text
    except Exception as e:
        print(f"Error reading PDF: {e}")
        return None

def generate_ai_summary(text):
    if not client: return "Error: GEMINI_API_KEY not found."
    if not text: return "Error: PDF Text extraction failed."
    
    print("Sending text to Gemini 2.5 Flash...")
    
    prompt = """
    You are an expert research assistant. Read the following academic paper text and generate a structured summary.
    
    The Output format must be in Markdown:
    ## 🧐 Problem Statement
    (What problem is this paper trying to solve?)
    
    ## 🛠️ Methodology
    (How did they solve it? What models or algorithms did they use?)
    
    ## 📊 Results & Impact
    (What were the key findings? Did they beat state-of-the-art?)
    
    Here is the paper text:
    """ + text[:50000] # Increased limit for Gemini 2.5
    
    try:
        # UPDATED CALL FOR NEW SDK
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt
        )
        return response.text
    except Exception as e:
        return f"AI Generation Failed. Error details: {str(e)}"

def save_paper_note(paper, ai_summary):
    if not os.path.exists("papers"):
        os.makedirs("papers")

    safe_title = re.sub(r'[^\w\-_\. ]', '', paper['title']).replace(' ', '_')[:40]
    filename = f"papers/{paper['date']}_{safe_title}.md"
    
    content = f"""# {paper['title']}

- **Category:** {paper['category']}
- **Published:** {paper['date']}
- **Source:** [Original ArXiv Link]({paper['link']})

---

{ai_summary}

---
*Generated by Gemini 2.5 Flash*
"""
    
    with open(filename, "w", encoding='utf-8') as f:
        f.write(content)
    print(f"Saved: {filename}")

if __name__ == "__main__":
    paper = fetch_random_paper()
    if paper:
        pdf_text = extract_text_from_pdf(paper['pdf_link'])
        summary = generate_ai_summary(pdf_text) 
        save_paper_note(paper, summary)
